In [2]:
print("Hello World")

Hello World


In [3]:
print("Hello Guys")

Hello Guys


In [5]:
surname = "Gray"
print("Hello Mrs....", surname)

Hello Mrs.... Gray


In [6]:
if 5 == 2:
    print("1 = 1")
else:
    print("The values are different")

The values are different


In [1]:
import random

In [4]:
#Task 1
myName = input("Hello! What is your?")
number = random.randint(1,10)
print("Well," + myName + "I am thinking of a number between 1 and 10.")
guess = int(input("Take a guess:"))

if guess == number:
    print("Good job," + myName + "! You guessed my number")
Else:print("Wrong, better luck next time")

Well,OlakI am thinking of a number between 1 and 10.
Wrong, better luck next time


In [7]:
#Task 2
print('Please Select your Favorite number between 1 and 100 for a joke?')
input()
print('Turtles is a bush baby, but bush baby is not a turtles!')
print()
print('Please Select your Favorite number between 1 and 100 for a joke?')
input()
print('why do people like to answer questions with another question?')
print()
print('Please Select your Favorite number between 1 and 100 for a joke?')
input()
print("The way you laugh gives endless laughs")

Please Select your Favorite number between 1 and 100 for a joke?
Turtles is a bush baby, but bush baby is not a turtles!

Please Select your Favorite number between 1 and 100 for a joke?
why do people like to answer questions with another question?

Please Select your Favorite number between 1 and 100 for a joke?
The way you laugh gives endless laughs


In [12]:
#Task 3
user_input = input("What is your favourite starter? ")
user_input1 = input("What is your favourite main course? ")
user_input2 = input("What is your favourite dessert? ")
user_input3 = input("What is your favourite drink? ")

print("Your favourite meal is....", user_input + ",", user_input1 + ",", user_input2 + ",", "with a glass of", user_input3)

Your favourite meal is.... Seedless Grape, Jollof Rice, Cake, with a glass of Coke


#NUMPY HOME LEARNING PROJECT

In [1]:
#Create a 1D array of numbers from 0 to 9
import numpy as np
x = np.arange(9)
print("Array from 0 to 9:")
print(x)

Array from 0 to 9:
[0 1 2 3 4 5 6 7 8]


In [2]:
##Create a 3×3 NumPy array of all Boolean value Trues
bool_arr = np.ones((3,3), dtype=bool)
print('3x3 Numpy Array: ')
print(bool_arr)

3x3 Numpy Array: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
#Extract all odd numbers from array of 1-10
x = np.arange(10)
print(x) 

# 2nd argument to add step above
arrayodd = np.arange(1, 10, 2)

print(arrayodd)


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [10]:
#Replace all odd numbers in an array of 1-10 with the value -1
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
odd_values = (a%2 == 1) 
a[odd_values] = -1 
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [18]:
#Convert a 1D array to a 2D array with 2 rows
array = np.array([20, 15, 10, 5, 25, 30])
newShape = array.reshape(2, 3) 

print(newShape)

[[20 15 10]
 [ 5 25 30]]


In [32]:
#Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
a = np.arange(3,12).reshape(3,3)
b = np.arange(12,21).reshape(3,3)
c = np.dot(a, b)
print(c)

total_sum = np.sum(c)
print(total_sum)

[[186 198 210]
 [321 342 363]
 [456 486 516]]
3078


In [36]:
#Create the following pattern without hardcoding. Use only NumPy functions.
array_1  = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])
array_2  = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 1, 2, 3, 1, 2, 3])

print(array_1 + array_2)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [35]:
array_1 = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

print(array_1)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
